# Generated by Django 4.2.29 on 2026-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1061_add_session_recording_trigger_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogflow",
            name="schedule_config",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
