# Generated by Django 4.2.29 on 2026-03-20 17:25

import django.db.models.deletion
from django.db import migrations, models

import posthog.models.utils


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1062_hogflow_schedule_config"),
        ("workflows", "0002_hogflowbatchjob_scheduled_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HogFlowScheduledRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=posthog.models.utils.UUIDT, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("run_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="workflows.hogflowbatchjob",
                    ),
                ),
                (
                    "hog_flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="scheduled_runs",
                        to="posthog.hogflow",
                    ),
                ),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to="posthog.team")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "run_at"], name="workflows_h_status_d8bde9_idx"),
                    models.Index(fields=["hog_flow", "-run_at"], name="workflows_h_hog_flo_cdf062_idx"),
                ],
            },
        ),
    ]
